---
title: "study-design"
format: pdf
bibliography: Studydesign.bib
csl: apa.csl
linestretch: 1.5

---

## Introduksjon

I denne oppgaven skal jeg sammenligne studier som ser på effekten av samtidig løps- og styrketrening på arbeidsøkonomi i løping. Løpsøkonomi (LØ) regnes vanligvis som en av tre bestemmende faktorer for utholdenhetsprestasjons, sammen med VO~2max~ og untyttingsgrad (toppidrett). Dermed vil det være fordelaktig for løpere å finne treningsmetoder som optimaliserer sin egen løpsøkonomi. LØ beskrives som energibehovet for en gitt hastighet, og blir som regel målt som oksygenopptaket på denne hastigheten. Jo bedre løpsøkonomi en utover har, jo lavere oksygenopptak vil personen ha på en gitt hastighet(toppidrett). LØ bestemmes av flere faktorer, og utenom teknikk, ser økt muskelstyrke, fjærstivhet og nevrale adaptasjoner ut til å være mest sentralt (toppidrett). Det er derfor interessant å undersøke hvordan samtidig løps- og styrketrening påvirker løpsøkonomien og generell prestasjon. Det har blitt observert bedring i RE allerede etter 4 uker hos godt trente utøvere [@guglielmoEffectsStrengthTraining2009]. Tilsvarende observasjoner har også blitt gjort i ulike studier som undersøker effektene fra 8-40 uker med styrketrening (@beattieEffectStrengthTraining2017; @storenMaximalStrengthTraining2008a; @taipaleStrengthTrainingEndurance2010; @milletEffectsConcurrentEndurance2002.

## Sammenligning av studiedesign og metoder

De fem studiene som jeg har valgt ønsket alle å undersøke hvordan samtidig løps- og styrketrening påvirker LØ og andre fysiologiske faktorer. Jeg har valgt og kun fokusere på LØ i denne oppgaven. Alle fem studiene er intervensjonsstudier som ser effektene av tung styrketrening og/eller eksplosiv styrketrening. Måten dette har blitt undersøkt på er i alle tilfellene ved å sammenligne resultater fra pre-tester med posttester. Alle studiene er gjort på godt trente utøvere, og vil dermed være begrenset til den populasjonen. LØ ble i alle studiene målt som oksygenopptak på en gitt submaksimal belastning på tredemølle.

For å svare på problemstillingen benyttet @milletEffectsConcurrentEndurance2002 og @storenMaximalStrengthTraining2008a et randomisert kontrollert studiedesign [@hulleyDesigningClinicalResearch2013]. Det blir oppgitt i begge artiklene at de ulike gruppene ble matchet for blant annet nivå, slik at gruppene skulle bli så lik som mulig. Det ble ikke oppgitt hvordan denne randomiseringen ble gjort, men det kan virke som at det ble brukt en "matched pair" randomisering. En slik randomisering brukes for å fordele forsøkspersoner med viktige karakteristikker, som for eksempel tid på 5000m, for å gjøre gruppene så lik som mulig [@hulleyDesigningClinicalResearch2013]. I @milletEffectsConcurrentEndurance2002 var 7 av deltakere på internasjonalt nivå, og disse ble dermed satt i par og fordelt på de to gruppene. I @storenMaximalStrengthTraining2008a ble gruppene matchet for alder og tid på 5000m. Begge studiene hadde mellom 15-19 deltakere, der halvparten av forsøkspersonene fungerte som kontrollgruppe. Med under 10 forsøkpersoner i hver gruppe, vil også en matchet randomisering være viktig for å unngå for store ulikheter mellom gruppene [@hulleyDesigningClinicalResearch2013]. I begge studiene var det en gruppe som trente tung styrketrening + løping, og en som kun trente løping. Utøverne gjennomførte en pre- og postest i laboratorium, hvor blant annet løpsøkonomien ble testet.

@taipaleStrengthTrainingEndurance2010 og @guglielmoEffectsStrengthTraining2009 undersøkte hvilken effekt kombinert løping med tung styrketrening og eksplosiv styrketrening har på løpsøkonomi. i begge studiene ble forsøkspersoner fordelt enten i en tung styrketrenings- eller eksplosiv styrketreningsgruppe. Begge studiene var randomiserte mixed model designs, der gruppene både ble sammenlignet mot hverandre, og med seg selv pre/post. I et slikt design kan forskere undersøke både innenfor- og mellomgruppeeffekter samtidig [@hulleyDesigningClinicalResearch2013]. @guglielmoEffectsStrengthTraining2009 hadde ikke en egen kontrollgruppe, men utøverne kan fungere som sin egen kontroll når effektene av styrketreningen ble sammenlignet med baseline-testene, som i et within subject design [@hulleyDesigningClinicalResearch2013].

Den siste studien @beattieEffectStrengthTraining2017 var en "two group repeated measures design", som gikk over 40 uker. 20 deltakere ble delt inn i en styrke+løping-gruppe og en kontrollgruppe. En svakhet med denne studien er mangel på randomisering [@hulleyDesigningClinicalResearch2013]. Utøverne ble fordelt i en av gruppen basert på blant annet hvor godt styrketrening passet i timeplanen deres, og hvor nære de bodde styrketreningfasiliteter. En slik inndeling kan føre til at utøvere som i utgangspunktet er svært motivert for styrke, og har troen på god effekt ender opp i intervensjonsgruppen. En slik fordeling kan ha innvirkning på hvor pålitelige resultatene i studien er [@hulleyDesigningClinicalResearch2013].

## Statistiske tester og resultat

For å undersøke effektene styrketrening har på løpsøkonomi har det blitt brukt flere ulike statistiske tester, avhengig av formålet. For å undersøke endring i LØ før og etter treningsintervensjone innad i gruppene brukte @milletEffectsConcurrentEndurance2002 og @storenMaximalStrengthTraining2008a en paret t-test. @milletEffectsConcurrentEndurance2002 "benyttet også en repeatead measures ANOVA" for å teste forskjellene mellom gruppene. De fant at gruppen som trente styrke + utholdenhet bedret LØ mer enn gruppen som bare trente utholdenhet (P \<0,05). Begge studiene brukte Pearson korrelasjontest for å undersøke sammenhengen mellom LØ og ulike styrkerelaterte variabler. @guglielmoEffectsStrengthTraining2009 brukte en tosidet ANOVA (group × time) for å teste hvordan gruppene "tung styrketrening" og "eksplosiv styrketrening" endret seg fra pre til post. De fant at "tung styrketrening" bedret LØ signifikant fra fra pre til post (P \<0,05), men fant ingen signifikant effekt i "eksplosiv styrke"-gruppen. En svakhet her er at det også hadde vært interessant å sammenligne gruppene seg imellom. @taipaleStrengthTrainingEndurance2010 undersøkte forskjell mellom gruppene med en "one way ANOVA" og forskjellene innad i gruppene med en "repeated measures ANOVA". Disse fant også at både tung styrketrening ser ut til å være mer effektivt enn eksplosiv styrketrening når sammenlignet pre/post. Gruppen med tung styrketrening økte LØ fra pre til post signifikant (P \<0,01). Til slutt @beattieEffectStrengthTraining2017 gjennomførte både, pre - mid - posttesting. De brukte "one way repeated measures anova" for hver gruppe, og "two-way repeated measures anova" for å sammenligne mellom gruppene. De fant en signifikant bedring i LØ fra uke 0-20 (P \<0,01), men ingen signifikant bedring fra uke 0-40. Det skal sies at utøverne trente styrke 2x ganger i uken fra ue 0-20, og 1x i uken fra uke 20-40. Dette kan være en årsak til at vi så en større effekt de første 20 ukene.

## Konklusjon

Overordnet viser resultatene fra studiene at tung styrketrening har en positiv effekt på arbeidsøkonomi i løping. Disse effektene ser vi både når styrketreningsgruppene har blitt sammenlignet med seg selv pre/post, og når sammenlignet med kontrollgrupper. Ut ifra disse studiene ser det også ut til at tung styrketrening har bedre effekt på LØ enn eksplosiv styrketrening. En svakhet er at ingen av disse studiene inkluderte kvinnelige forsøkspersoner. I nyere studier som undersøker dette tema burde kvinner også inkluderes, for å undersøke om effektene styrketrening har på LØ også er representativt for kvinner. Basert på disse studiene ser det også ut til at to økter i uken er mer optimalt enn en økt i uken. \newpage

### Referanser
